local get_outfit_ap_res     = grok_actor_damage_balancer.get_outfit_ap_res
local get_outfit_immunity   = grok_actor_damage_balancer.get_outfit_immunity
local clamp                 = _g.clamp
local smallest				= 0.0000001
local ceil					= math.ceil
local min                   = math.min
local max                   = math.max
local wepl                  = wepl_hit_effect.actor_on_before_hit
--local utjan					= utjan_traits
--local haru					= haru_skills
local health_gating_flag    = false
local health_gating_active  = false

local FX_Play 		= gamma_diff_utils.FX_Play
local play_sound	= gamma_diff_utils.play_sound
local trim_ammo		= gamma_diff_utils.trim_ammo
local combat_log	= gamma_diff_utils.combat_log
local tn			= gamma_diff_utils.trim_number

local ini_adb               = ini_file_ex("plugins\\gamma_actor.ltx")

-- Kill wepl's original function to ENSURE it actually works.
function wepl_hit_effect.actor_on_before_hit(shit, bone_id, flags) end

-- Kill Haruka's Skills to ensure it works too
--function haru_skills.actor_on_before_hit(shit)
--end

local function load_defaults()
	local t = {}
	local op = gamma_diff_mcm.op
	for i, v in ipairs(op.gr) do
		if v.def ~= nil then
			t[v.id] = v.def
		end
	end
	return t
end

local settings = load_defaults()

local function load_settings()
	settings = load_defaults()
	if ui_mcm then
		for k, v in pairs(settings) do
			settings[k] = ui_mcm.get("gamma_diff/" .. k)
		end
	end
end

local function trace(str, ...)
	if settings.debug == 2 then
		printf("[G.A.M.M.A. THE THING] ADB: " .. str, ...)
	end
end

function keep_alive()
	if time_global() - health_gating_tg > max(tonumber(ini_adb:r_string_ex("adb_actor", "health_gate_time") or 0), 0) then
		health_gating_flag = false
		health_gating_active = false
		trace('HEALTH GATE EXPIRED')
		UnregisterScriptCallback("actor_on_update", keep_alive)
	end
end

local pba = perk_based_artefacts
function perk_based_artefacts.actor_on_before_hit(s_hit, bone_id, flags) end
function perk_based_artefacts.actor_on_hit_callback(obj, amount, local_direction, who, bone_index) end
function perk_based_artefacts.actor_on_before_death(whoID, flags) end

function PBA_a_obh(shit, bone_id, flags)
	trace('Firing PBA >> actor_on_before_hit')
	pba.last_hit = hit(shit)
	pba.process_artefacts(pba.artefact_on_before_hit_functions, shit, bone_id, flags)
end

function PBA_a_ohc(obj, amount, local_direction, who, bone_index)
	trace('Firing PBA >> actor_on_hit_callback')
	pba.process_artefacts(pba.artefact_on_hit_functions, obj, amount, who, last_hit)
end

local flags = { ret_value = true }

function PBA_a_obd(whoID, flags)
	trace('Firing PBA >> actor_on_before_death')	flags.ret_value = false
	pba.process_artefacts(pba.artefact_on_before_death_functions, whoID, flags)
end

function damage_math(shit, scale, total_prot, af_prot, bo_prot, ca_prot)
	
	if shit.power <= 0 then return end

	local sc = scale and scale or 1
	local tp = total_prot and total_prot or 0
	local ap = af_prot and af_prot or 0
	local bp = bo_prot and bo_prot or 0
	local cp = ca_prot and ca_prot or 0
	local dm = 0

	dm = (shit.power * sc) * (1 - tp) * (1 - ap) * (1 - bp) * (1 - cp)
	trace('Damage: %s >> (%s x %s) x (1.0 - %s) x (1.0 - %s) x (1.0 - %s) x (1.0 - %s)', dm, shit.power, sc, tp, ap, bp, cp)
	return dm or 0
end

local zone_last = {}
local zone_field_last = {}
local zone_ball_last = {}
local hit_last = {}
local fall_last = {}
function clear_invuls()
	zone_last = {}
	zone_field_last = {}
	zone_ball_last = {}
	hit_last = {}
	fall_last = {}
end

local hitboxes={}
	hitboxes[19]	=	"head"
	hitboxes[17]	=	"head"
	hitboxes[16]	=	"head"
	hitboxes[15]	=	"head"
	hitboxes[14]	=	"head"
	hitboxes[13]	=	"torso"
	hitboxes[12]	=	"torso"
	hitboxes[11]	=	"torso"
	hitboxes[2]		=	"torso"
	hitboxes[20]	=	"arms"
	hitboxes[21]	=	"arms"
	hitboxes[22]	=	"arms"
	hitboxes[23]	=	"arms"
	hitboxes[33]	=	"arms"
	hitboxes[34]	=	"arms"
	hitboxes[35]	=	"arms"
	hitboxes[36]	=	"arms"
	hitboxes[3]		=	"legs"
	hitboxes[4]		=	"legs"
	hitboxes[7]		=	"legs"
	hitboxes[8]		=	"legs"

local hitbox_mult = 
{
    ["head"] 		= 0.8,
    ["torso"] 		= 0.9,
    ["arms"] 		= 0.85,
    ["legs"] 		= 0.85,
}

difficulty_multiplier =
{
	[1] = 0.65,
	[2] = 0.8,
	[3] = 1.0,
	[4] = 1.2,
}

degrade_multiplier =
{
	[1] = 0.7,
	[2] = 0.85,
	[3] = 1.0,
	[4] = 1.0,
}

local hit_type_id = 
{
	[0]  = "Burn",
	[1]  = "Shock",
	[2]  = "Chemical Burn",
	[3]  = "Radiation",
	[4]  = "Psychic",
	[5]  = "Rupture",
	[6]  = "Bullet",
	[7]  = "Impact",
	[8]  = "Explosive",
	[9]	 = "Rupture (wound_2)",
	[10] = "Burn (light_burn)",
}

function get_protection(shit, bone_id, k_ap)
	
	-- Fallback defaults
	immunity = "strike_immunity"
	protection = "Strike"
	booster_type_def = 14
	adjuster = 1.5
	limiter = 0.8
	absorb = 0.0
	bleed = 0.1
	scale = 0.5
	arti = 1.0
	booster = 1.0

	if ini_adb:section_exist("adb_dmg_" .. shit.type) then
		get_adb 			= "adb_dmg_" .. shit.type
		immunity 			= ini_adb:r_string_ex(get_adb, "immunity")
		protection 			= ini_adb:r_string_ex(get_adb, "protection")
		booster_type_def	= tonumber(ini_adb:r_string_ex(get_adb, "booster_type_def"))
		adjuster			= max(smallest, tonumber(ini_adb:r_string_ex(get_adb, "adjuster")))
		limiter				= clamp(tonumber(ini_adb:r_string_ex(get_adb, "limiter")), smallest, 1.0)
		absorb				= max(tonumber(ini_adb:r_string_ex(get_adb, "absorb")), (-1 + smallest))
		bleed				= max(tonumber(ini_adb:r_string_ex(get_adb, "bleed")), 0)
		scale				= max(tonumber(ini_adb:r_string_ex(get_adb, "scale")), smallest)
		arti				= max(tonumber(ini_adb:r_string_ex(get_adb, "arti")), 0)
		booster				= max(tonumber(ini_adb:r_string_ex(get_adb, "booster")), 0)
	end

	total_prot = 0.0
	bonus_durability = 0.0
	bonus_durability_h = 0.0
	headshot = 0
	elem = 0

	if hitboxes[bone_id] == "head" then
		headshot = 1
	end

	if shit.type ~= hit.fire_wound then
		headshot = 0
		elem = 1
	end

	local armor_protection = 0
	local armor_bone_value = 0
	local outfit = db.actor:item_in_slot(7)
	if (outfit) then
		local cond = outfit:condition()
		local c_outfit = outfit:cast_CustomOutfit()
		if (c_outfit) then
			
			bonus_durability = get_outfit_immunity(outfit, immunity)
		
			if shit.type == hit.fire_wound then
				armor_protection = c_outfit:GetBoneArmor( BoneID["bip01_spine"] ) * cond * adjuster or 0
				bonus_durability = c_outfit:GetBoneArmor( BoneID["bip01_spine"] ) * adjuster or 0
			else
				armor_protection = c_outfit:GetDefHitTypeProtection(shit.type) * cond * adjuster or 0
				bonus_durability = c_outfit:GetDefHitTypeProtection(shit.type) * adjuster or 0
			end
			
			armor_hit_frac = ini_sys:r_float_ex(outfit:section(), "hit_fraction_actor") or 1
			armor_bone_value = (1 - armor_hit_frac) * cond * 0.75 or 0
			
			if (headshot == 0 and elem == 0) or elem == 1 then
				trace('Armor >> Protection: %s // Bonus durability: %s', tn(armor_protection), tn(bonus_durability))
				if shit.type == hit.fire_wound then
					trace('Armor >> BR amount: %s', tn(armor_bone_value))
				end
			end
		end
	end

	local helmet_protection = 0
	local helmet_bone_value = 0
   	local helmet = db.actor:item_in_slot(12)
    	if (helmet) then
		local cond = helmet:condition()
		local c_helmet = helmet:cast_Helmet()
		if (c_helmet) then    
			
			bonus_durability_h = get_outfit_immunity(helmet, immunity)
			
			if shit.type == hit.fire_wound then
				helmet_protection = c_helmet:GetBoneArmor( BoneID["bip01_head"] ) * cond * adjuster or 0
				bonus_durability_h = c_helmet:GetBoneArmor( BoneID["bip01_head"] ) * adjuster or 0
			else
				helmet_protection = c_helmet:GetDefHitTypeProtection(shit.type) * cond * adjuster or 0
				bonus_durability_h = c_helmet:GetDefHitTypeProtection(shit.type) * adjuster or 0
			end
			
			helmet_hit_frac = ini_sys:r_float_ex(helmet:section(), "hit_fraction_actor") or 1
			helmet_bone_value = (1 - helmet_hit_frac) * cond or 0
			
			if (headshot == 1 and elem == 0) or elem == 1 then
				trace('Helmet >> Protection: %s // Bonus durability: %s', tn(helmet_protection), tn(bonus_durability_h))
				if shit.type == hit.fire_wound then
					trace('Helmet >> BR amount: %s', tn(helmet_bone_value))
				end
			end
		end
	end

	if elem == 0 then
		if headshot == 1 then
			armor_bone_value = 0
			armor_protection = 0
		else
			helmet_bone_value = 0
			helmet_protection = 0
		end
	else
		headshot = 0
	end

	-- Artefacts protection
	local artefacts_protection = 0
	local artefacts_ap_res = 0
	af_bone_value = 0
	af_prot_value = 0
	db.actor:iterate_belt(
		function(owner, obj)
			local sec = obj:section()
			local cond = obj:condition()

			local immunities_sec = ini_sys:r_string_ex(sec, "hit_absorbation_sect")
			af_prot_value = ini_sys:r_float_ex(immunities_sec, immunity) * cond

			if sec == "af_kevlar" then
				af_bone_value = 0.00
			end
			if sec == "af_kevlar_up" then
				af_bone_value = 0.01
			end
			if sec == "af_plates" then
				af_bone_value = 0.02
			end
			if sec == "af_plates_up" then
				af_bone_value = 0.03
			end

			if headshot == 1 then
				if sec == "af_kevlar" or sec == "af_kevlar_up" or sec == "af_plates" or sec == "af_plates_up" then
					prot = 0
					af_bone_value = 0
				end
			end

			if af_prot_value >= 0 then
				af_prot_value = af_prot_value * 0.5 * arti
			end

			artefacts_protection = artefacts_protection + af_prot_value
			artefacts_ap_res = artefacts_ap_res + af_bone_value
		end	
	)

	if artefacts_ap_res ~= 0 then
		trace('Artefacts BR: %s >> Total BR: %s', tn(artefacts_ap_res), tn(armor_bone_value + artefacts_ap_res))
	end

	-- Booster protection
	local booster_protection = 0
	db.actor:cast_Actor():conditions():BoosterForEach( function(booster_type, booster_time, booster_value)
		if booster_type == booster_type_def then
			booster_protection = booster_value
		end
	end)

	booster_protection = booster_protection * booster
	
	catch_bonus = 0
	-- Special case if ammo do not penetrate armor
	no_pen = 0 
	if shit.type == hit.fire_wound then
		if headshot == 1 then
			trace('Penetration math >> Ammo pen: %s // Helmet BR: %s', tn(k_ap), tn(helmet_bone_value))
			if k_ap < helmet_bone_value then
				--helmet_protection = helmet_protection * 0.2 + helmet_bone_value * 1.3
				--trace("Bullet caught! >> Protection: %s", tn(helmet_protection))
				catch_bonus = helmet_bone_value
				no_pen = 1
			end
		else
			armor_bone_value = armor_bone_value + artefacts_ap_res
			trace('Penetration math >> Ammo pen: %s // Armor BR: %s', tn(k_ap), tn(armor_bone_value))
			if k_ap < armor_bone_value then
				--armor_protection = armor_protection * 0.2 + armor_bone_value * 1.3
				--trace("Bullet caught! >> Protection: %s", tn(armor_protection))
				catch_bonus = armor_bone_value
				no_pen = 1
			end
		end

		if settings.particles == 2 then
			if no_pen == 1 then
				FX_Play("pfx_armor", db.actor, shit, db.actor:bone_name(bone_id))
			else
				FX_Play("pfx_flesh", db.actor, shit, db.actor:bone_name(bone_id))
			end
		end
	end
	
	fall_damage = 0
	if (shit.type == hit.strike) and (shit.draftsman:id() == db.actor:id()) then
		-- AFAIK, the *only* way to deal strike damage to yourself is through falling.
		-- So, get better, don't trip.
		trace('Damage instance was most likely fall damage')
		helmet_protection = 0
		armor_protection = 0
		fall_damage = 0 -- 1
		-- Dunno about this mechanic tbh, poltergeists can delete you
	end
	
	total_prot = (helmet_protection + armor_protection)

	if shit.type ~= hit.radiation then
		if zone_field == 1 then
			if total_prot >= 0 then
				total_prot = total_prot * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_field_protection") or 1), smallest)
			end
			if artefacts_protection >= 0 then
				artefacts_protection = artefacts_protection * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_field_protection") or 1), smallest)
			end
			if booster_protection >= 0 then
				booster_protection = booster_protection * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_field_protection") or 1), smallest)
			end
		end
		if zone_dot == 1 then
			if total_prot >= 0 then
				total_prot = total_prot * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_mine_protection") or 1), smallest)
			end
			if artefacts_protection >= 0 then
				artefacts_protection = artefacts_protection * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_mine_protection") or 1), smallest)
			end
			if booster_protection >= 0 then
				booster_protection = booster_protection * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_mine_protection") or 1), smallest)
			end
		end
	end
	
	total_prot = min(total_prot, limiter and limiter or 1.00)
	artefacts_protection = min(artefacts_protection, limiter and limiter or 1.00)
	booster_protection = min(booster_protection, limiter and limiter or 1.00)
	catch_bonus = min(catch_bonus, limiter and limter or 1.00)

	trace('Total protection (physical): %s >> (%s + %s)', tn(total_prot), tn(helmet_protection), tn(armor_protection))
	trace('Total protection (af+boost): %s // %s', tn(artefacts_protection), tn(booster_protection))

	af_prot = artefacts_protection or 0
	bo_prot = booster_protection or 0
	ca_prot = catch_bonus or 0
end

function shit_booster(shit, bone_id, k_ap)
	
	k_ap = (k_ap and k_ap or 0) * 10
	
	get_protection(shit, bone_id and bone_id or "bip01_spine", k_ap and k_ap or 0)

	damage = (shit.power * scale)

	damage = damage * (1 - total_prot)

	zone_mult = 1
	if shit.type ~= hit.radiation and shit.type ~= hit.telepatic then
		if zone_field == 1 then
			zone_mult = max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_field_damage") or 1), smallest)
		end
		if zone_dot == 1 then
			zone_mult =  max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_mine_damage") or 1), smallest)
		end
	end

	damage = damage * zone_mult
	
	degrade_math = (damage * (0.07 * (1.0 + absorb)))
	degrade_math = degrade_math * degrade_multiplier[game_num]

	PBA_a_obh(shit, bone_id, flags)		-- Call PBA before any armor math takes place. This makes the Black Angel useful.
	wepl(shit, bone_id, flags)			-- Also call wepl before shit.power = 0 to ensure it actually works.

	damage = damage_math(shit, scale, total_prot, af_prot, bo_prot, ca_prot) or 0 -- or 0 just in case?
	damage = damage * zone_mult

	if shit.type == hit.fire_wound then
		damage = damage / f_dist
	end

	-- Psy stress compatibility
	if stress_mcm then
		if arszi_psy.get_psy_wound_stress and shit.power > 0 then
			c_psy_hit_stress_multiplier = ( stress_mcm.get_config("hit_stress") or 2.8 ) / 100

			local h = hit()
			h.power = clamp((damage * 2) * c_psy_hit_stress_multiplier, 0, 0.5)
			h.direction = device().cam_dir
			h.bone = "bip01_head"
			h.draftsman = db.actor
			h.impulse = 0
			h.type = hit.telepatic

			trace('Stressful Zone detected >> Dealing psy hit: %s power', tn(h.power))

			db.actor:hit(h)

		end
	end

	if fall_damage == 1 then
		degrade_math = 0
		bleed = bleed * 2
		damage = damage * 2
	end
	
	if shit.type == hit.telepatic or shit.type == hit.radiation then
		degrade_math = 0
	end
	
	if zone_field == 1 then
		degrade_math = degrade_math * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_field_degrade") or 1), smallest)
	end
	if zone_dot == 1 then
		degrade_math = degrade_math * max(tonumber(ini_adb:r_string_ex("adb_actor", "zone_mine_degrade") or 1), smallest)
	end

	if shit.type == hit.fire_wound and no_pen == 0 then
		degrade_math = degrade_math * 0.5
	end
	
	degrade_o = 0
	degrade_h = 0

	if (headshot == 1 and elem == 0) or elem == 1 then
		helmet = db.actor:item_in_slot(12)
        if helmet then
			degrade_math = degrade_math / (1.0 + max(smallest, bonus_durability_h))
		    cond = helmet:condition()
		    helmet:set_condition(cond - degrade_math)
			degrade_h = degrade_math
		end
	end

	if (headshot == 0 and elem == 0) or elem == 1 then
		armor = db.actor:item_in_slot(7)
        if armor then
			degrade_math = degrade_math / (1.0 + max(smallest, bonus_durability))
		    cond = armor:condition()
		    armor:set_condition(cond - degrade_math)
			degrade_o = degrade_math
        end
	end

	trace('Armor degradation: %s // Helmet degradation: %s', tn(degrade_o), tn(degrade_h))

	PBA_a_ohc(db.actor, damage, shit.direction, shit.draftsman, bone_id)
	
	health_gating_flag = health_gating_active 
	or ( db.actor.health >= tonumber(ini_adb:r_string_ex("adb_actor", "health_gate_trigger")) 
		and db.actor.health - damage <= max(tonumber(ini_adb:r_string_ex("adb_actor", "health_gate_trigger") or 1), 0) )
	
	if health_gating_flag then
		if not health_gating_active then
			health_gating_flag = true
			health_gating_active = true
			health_gating_tg = time_global()
			trace('HEALTH GATE TRIGGERED')
			RegisterScriptCallback("actor_on_update", keep_alive)
		end
	end

	old_health = db.actor.health

	if shit.type == hit.telepatic then
		damage = 0
	end
	
	if shit.type ~= hit.radiation then
		if not health_gating_active then
			if (db.actor.health - damage) <= 0 then
				PBA_a_obd(db.actor, flags)
			end
			db.actor:set_health_ex(db.actor.health - damage)
		else
			min_health = max(tonumber(ini_adb:r_string_ex("adb_actor", "health_gate_limit") or 1), 0)
			if self_inflicted == 0 then
				if db.actor.health - damage <= min_health then
					db.actor:set_health_ex(min_health)
					trace('HEALTH GATED SUCCESSFULLY')
				else
					db.actor:set_health_ex(max( (db.actor.health - damage), min_health))
				end
			else

				if (db.actor.health - damage) <= 0 then
					PBA_a_obd(db.actor, flags)
				end
				
				db.actor:set_health_ex(db.actor.health - damage)
				trace('HEALTH GATE BYPASSED (Self inflicted)')
			end
		end
	end
	
	if shit.type == hit.radiation then
		if self_inflicted == 1 then
			db.actor:change_radiation(damage)
		else
			local dice = math.ceil((total_prot - 50) / 2)
			if dice > 0 then
				if math.random(100) > dice then
					db.actor:change_radiation(damage * 2.0)
				end
			else
				db.actor:change_radiation(damage * 2.0)
			end
		end
	end

	new_health = db.actor.health

	trace('Old health: %s // New health: %s', old_health, new_health)

	if zone_dot == 0 then
		if no_pen == 1 then
			db.actor:cast_Actor():conditions():AddWound(damage * bleed * 0.25, hit_type, bone_id)
		else
			db.actor:cast_Actor():conditions():AddWound(damage * bleed, hit_type, bone_id)
		end
	end

	if shit.type ~= hit.radiation or (shit.type == hit.radiation and damage >= 0.005) then
		if shit.type == hit.fire_wound then
			combat_log('%s || Struck by %s (%s) with %s (%s) in the %s for %s damage from %s meters (%sx). (%s -> %s)', time_global(), shit.draftsman:section(), shit.draftsman:id(), wpn_sec, amm_sec, hitboxes[bone_id] or "whole body", tn(damage), tn(dist), tn(1 / f_dist), tn(old_health), tn(db.actor.health))
		else
			combat_log('%s || Struck by %s (%s) for %s damage (%s). (%s -> %s)', time_global(), shit.draftsman:section(), shit.draftsman:id(), tn(damage), hit_type_id[shit.type], tn(old_health), tn(db.actor.health))
		end
	end

	if db.actor.health < 0 then
		db.actor.health = 0
	end

	if db.actor.health <= 0 and db.actor.health - damage <= -0.5 and settings.gibs == 2 then
		FX_Play("pfx_gibs", db.actor, shit, db.actor:bone_name(bone_id))
		play_sound("gore\\hit_zombie_"..math.random(23), 1.0, db.actor)
	end

	shit.power = 0.0
end


function actor_on_before_hit(shit, bone_id, flags)

	if not shit.draftsman then
		return
	end

	if not db.actor:alive() then
		shit.power = 0
		flags.ret_value = 0
		return
	end

	if shit.power == 0 then
		--flags.ret_value = 0
		return
	end

	if shit.type == 4 then
		--shit.power = 0
		--flags.ret_value = 0
		return 
	end

	if (shit.power == 0.001 and shit.impulse == 0.001) then
		flags.ret_value = 0
		return
	end

	self_inflicted = 0
	if shit.draftsman:id() == db.actor:id() then
		self_inflicted = 1
	end

	actor = db.actor
	shooter = shit.draftsman
	balancer = "adb_balance"
	
	zone_dot = 0
	zone_field = 0
	
		gameplay = alife_storage_manager.get_state().diff_game
		if not (type(gameplay) == "table") then
			alife_storage_manager.get_state().diff_game = {}
			alife_storage_manager.get_state().diff_game["type"] = game_num
			gameplay = alife_storage_manager.get_state().diff_game
		end
		game_num = gameplay["type"] or game_num
		
		shit.power = shit.power * difficulty_multiplier[game_num]
	
	if shooter and shooter:has_info("npcx_is_companion") then
		flags.ret_value = false
		shit.power = 0
		return
	end

	trace(' ')
	trace('You got hit! >> tg: %s // power: %s // where: %s // mult: %s // who: %s (%s)', time_global(), tn(shit.power), hitboxes[bone_id] or "whole body", difficulty_multiplier[game_num], shit.draftsman:section(), shit.draftsman:id())

	invul_frac 				= max(tonumber(ini_adb:r_string_ex("adb_actor", "invul_frac") or 1), ceil(smallest))
	invul_time_bullet 		= max(tonumber(ini_adb:r_string_ex("adb_actor", "invul_time_bullet") or 1), 0)
	invul_time_zone_mine	= max(tonumber(ini_adb:r_string_ex("adb_actor", "invul_time_zone_mine") or 1), 0)
	invul_time_zone_field	= max(tonumber(ini_adb:r_string_ex("adb_actor", "invul_time_zone_field") or 1), 0)
	invul_time_zone_ball	= max(tonumber(ini_adb:r_string_ex("adb_actor", "invul_time_zone_gall") or 1), 0)
	invul_time_strike_self	= max(tonumber(ini_adb:r_string_ex("adb_actor", "invul_time_strike_self") or 1), 0)

	if (shit.type == hit.fire_wound) then
		wpn = level.object_by_id(shit.weapon_id)

		if wpn == nil then return end

		local sec = wpn:section()
		local wpn_id = wpn:id()

		local hit_power 		= game_difficulties.get_game_factor("hit_power") and game_difficulties.get_game_factor("hit_power") or 1

		dist = db.actor:position():distance_to(shit.draftsman:position()) or 1

		local ammo_type_number = wpn:get_ammo_type()
		local ammo_list = utils_item.get_ammo(sec, wpn_id)
		local ammo_section = ammo_list[ammo_type_number+1]

		if string.find(sec, "helicopter_strong") or string.find(sec, "helicopter_weak") or string.find(sec, "mounted_weapon") or string.find(sec, "stationary_gun") then
			ammo_section = ini_sys:r_string_ex(sec, "ammo_class")
		end

		if ammo_section == nil then return end

		k_ap 	= ini_sys:r_float_ex(ammo_section, "k_ap") or 0
		air_res	= ini_sys:r_float_ex(ammo_section, "k_air_resistance") or 0.05
		
		trace('Bullet hit >> weapon: %s // ammo: %s', sec, ammo_section)

		-----------------------------------------------------------
		local kind				= ini_sys:r_string_ex(sec, "kind")
		local k_mod				= 3.0

		if kind == "w_sniper" then
			k_mod 				= 9.0
		end

		local weapon_speed		= utils_item.get_param(sec, wpn_id, "bullet_speed", "float", true) or 1000
		local bullet_speed		= ini_sys:r_float_ex(ammo_section, "k_bullet_speed", "float", true) or 1
		local f_speed			= weapon_speed * bullet_speed * 0.7 --normalize((weapon_speed * bullet_speed) * 0.7, 0, 1000)
		local f_time			= (dist / f_speed) * k_mod			-- Values are extreme because this is highly experimental!!
		local m_dist			= f_time * f_speed
		f_dist					= ( 1 + m_dist / 200 * ( air_res * 0.5 / ( 1 - air_res + 0.1 )))
		local o_dist			= ( 1 + dist / 200 * ( air_res * 0.5 / ( 1 - air_res + 0.1 )) )

		local eff_dist			= math.min(math.max(smallest, ini_adb:r_float_ex("gbo_ranges", kind) or 1.0), 1.0) or smallest
		eff_dist				= math.ceil(f_speed * eff_dist)

		if dist <= eff_dist then
			f_dist = 1.0
		else
			f_time = ((dist - eff_dist) / f_speed) * k_mod
			m_dist = f_time * f_speed
			f_dist = ( 1 + (m_dist) / 200 * ( air_res * 0.5 / ( 1 - air_res + 0.1 )) )
			f_dist = math.max(1.0, f_dist)
		end
		-----------------------------------------------------------
		
		buckshot = ini_sys:r_float_ex(ammo_section, "buck_shot") and ini_sys:r_float_ex(ammo_section, "buck_shot") or 0
		ricochet = ini_sys:r_bool_ex(ammo_section, "allow_ricochet") and ini_sys:r_bool_ex(ammo_section, "allow_ricochet") or true

		-- Trim the ammo_section name
		ammo_section = trim_ammo(ammo_section)

		wpn_sec = sec or "something"
		amm_sec = ammo_section or "a bullet maybe"
		
		if ini_adb:line_exist(balancer, ammo_section) then
			ammo_mult = (tonumber(ini_adb:r_string_ex(balancer, ammo_section) or 1))
			shit.power = shit.power * ammo_mult
			trace('Ammo has multiplier under [adb_balance] >> ammo_mult: x %s', ammo_mult)
		end
		
		body_part = hitboxes[bone_id]
		body_mult = hitbox_mult[body_part] or hitbox_mult["legs"]
		shit.power = shit.power * body_mult --* hit_power

		trace('Body part multiplier >> body_mult: x %s', body_mult)

		if buckshot > 1 or ricochet == 0 then
			shit_booster(shit, bone_id, k_ap)
			shit.power = 0
			flags.ret_value = false
			return
		end
		
		if hit_last[shit.draftsman:id()] then
			if time_global() - hit_last[shit.draftsman:id()] >= (1000/invul_frac) * invul_time_bullet then
				hit_last[shit.draftsman:id()] = time_global()
				shit_booster(shit, bone_id, k_ap)
				shit.power = 0
				flags.ret_value = false
				return
			else
				trace('Last hit was less than %s ms ago, SKIPPING!', tn((1000/invul_frac) * invul_time_bullet))
				combat_log('%s || MULTIHIT LOCKOUT || %s (%s) tried to hit you with %s (%s).', time_global(), shit.draftsman:section(), shit.draftsman:id(), wpn_sec, amm_sec)
				shit.power = 0
				flags.ret_value = false
				return
			end
		else
			hit_last[shit.draftsman:id()] = time_global()
			shit_booster(shit, bone_id, k_ap)
			shit.power = 0
			flags.ret_value = false
			return
		end
		
		if old_power then
			shit.power = old_power
		end
		
		return
		
	end
	
	local zone_forced = 0
	local zone_field_forced = 0
	if (shit.type ~= hit.radiation) and (shit.type ~= hit.telepatic) then
		
		trace('Elemental hit >> shit.type: %s', hit_type_id[shit.type])

		-- Fix some HILARIOUS default values
		if string.find(shit.draftsman:name(), "zone_mine_field_soc") then
			shit.power = shit.power / 15
			-- These mines deal 35 (THIRTY FIVE) damage!
			-- 3.5 makes them at least survivable without triggering the Health Gate
		end
		
		-- Force all of these to be processed as zone_mine
		if string.find(shit.draftsman:name(), "burning_fuzz")
		or string.find(shit.draftsman:name(), "buzz")				-- Unused?
		or string.find(shit.draftsman:name(), "gravi_zone")			-- Might be the VERY RARE SoC anomalies (I've seen them in Radar and in CNPP South)
		or string.find(shit.draftsman:name(), "generator_")			-- Has damage defined (and it's A LOT)
		or string.find(shit.draftsman:name(), "hvatalka")			-- Unused
		or string.find(shit.draftsman:name(), "liana")				-- Unused
		or string.find(shit.draftsman:name(), "monolith")			-- Has damage defined
		or string.find(shit.draftsman:name(), "mosquito_bald")		-- Unused, funny name
		or string.find(shit.draftsman:name(), "no_gravity")			-- Unused
		or string.find(shit.draftsman:name(), "sarcofag")			-- Unused?
		or string.find(shit.draftsman:name(), "student")			-- Unused?
		or string.find(shit.draftsman:name(), "witches")			-- Central Pripyat shock anomalies
		or string.find(shit.draftsman:name(), "zharka") then		-- Maybe up north too, for sure it's not unused
			zone_forced = 1
		end


		if (string.find(shit.draftsman:name(), "_mine_") or zone_forced == 1) and shit.power <= 0.2 then
			
			zone_dot = 1
			
			if zone_last[shit.draftsman:id()] then
				if time_global() - zone_last[shit.draftsman:id()] >= (1000/invul_frac) * invul_time_zone_mine then
					zone_last[shit.draftsman:id()] = time_global()
					shit_booster(shit, bone_id)
					shit.power = 0
					flags.ret_value = false
					return
				else
					trace('Last damage tick was less than %s ms ago, SKIPPING!', tn((1000/invul_frac) * invul_time_zone_mine))
					combat_log('%s || MULTIHIT LOCKOUT || %s (%s) tried to hit you. (%s)', time_global(), shit.draftsman:section(), shit.draftsman:id(), shit.type)
					shit.power = 0
					flags.ret_value = false
					return
				end
			else
				zone_last[shit.draftsman:id()] = time_global()
				shit_booster(shit, bone_id)
				shit.power = 0
				flags.ret_value = false
				return
			end
			
			return
		end

		if string.find(shit.draftsman:name(), "_field_") then
			zone_field = 1
			
			if zone_field_last[shit.draftsman:id()] then
				if time_global() - zone_field_last[shit.draftsman:id()] >= (1000/invul_frac) * invul_time_zone_field then
					zone_field_last[shit.draftsman:id()] = time_global()
					shit_booster(shit, bone_id)
					shit.power = 0
					flags.ret_value = false
					return
				else
					trace('Last damage tick was less than %s ms ago, SKIPPING!', tn((1000/invul_frac) * invul_time_zone_field))
					combat_log('%s || MULTIHIT LOCKOUT || %s (%s) tried to hit you. (%s)', time_global(), shit.draftsman:section(), shit.draftsman:id(), shit.type)
					shit.power = 0
					flags.ret_value = false
					return
				end
			else
				zone_field_last[shit.draftsman:id()] = time_global()
				shit_booster(shit, bone_id)
				shit.power = 0
				flags.ret_value = false
				return
			end
			
			return
		end

		if string.find(shit.draftsman:name(), "fireball_") then
			zone_ball = 1

			if zone_field_last[shit.draftsman:id()] then
				if time_global() - zone_field_last[shit.draftsman:id()] >= (1000/invul_frac) * invul_time_zone_ball then
					zone_ball_last[shit.draftsman:id()] = time_global()
					shit_booster(shit, bone_id)
					shit.power = 0
					flags.ret_value = false
					return
				else
					trace('Last damage tick was less than %s ms ago, SKIPPING!', tn((1000/invul_frac) * invul_time_zone_ball))
					combat_log('%s || MULTIHIT LOCKOUT || %s (%s) tried to hit you. (%s)', time_global(), shit.draftsman:section(), shit.draftsman:id(), shit.type)
					shit.power = 0
					flags.ret_value = false
					return
				end
			else
				zone_ball_last[shit.draftsman:id()] = time_global()
				shit_booster(shit, bone_id)
				shit.power = 0
				flags.ret_value = false
				return
			end
			
			return
		end

		if shit.draftsman:id() == db.actor:id() and shit.type == hit.strike then
			if fall_last[shit.draftsman:id()] then	-- Tabling your own ID??? NONSENSE
				if time_global() - fall_last[shit.draftsman:id()] >= (1000/invul_frac) * invul_time_strike_self then
					fall_last[shit.draftsman:id()] = time_global()
					shit_booster(shit, bone_id)
					shit.power = 0
					flags.ret_value = false
					return
				else
					trace('Last fall damage (maybe) instance was less than %s ms ago, SKIPPING!', tn((1000/invul_frac) * invul_time_strike_self))
					combat_log('%s || MULTIHIT LOCKOUT || Too many fall damage instances!', time_global())
					shit.power = 0
					flags.ret_value = false
					return
				end
			else
				fall_last[shit.draftsman:id()] = time_global()
				shit_booster(shit, bone_id)
				shit.power = 0
				flags.ret_value = false
				return
			end
			
			return
		end

		shit_booster(shit, bone_id)
		shit.power = 0
		flags.ret_value = false
		return
	end
	
	if shit.type == hit.radiation then
		shit_booster(shit, bone_id)
		shit.power = 0
		flags.ret_value = false
		return
	end

	shit.power = 0
	flags.ret_value = false
	return
end

function on_game_start()
	RegisterScriptCallback("actor_on_first_update", load_settings)
	RegisterScriptCallback("actor_on_before_hit", actor_on_before_hit)
	RegisterScriptCallback("on_option_change", load_settings)
	RegisterScriptCallback("actor_on_first_update", clear_invuls)
	RegisterScriptCallback("on_level_changing", clear_invuls)
end